### PR TITLE
fix: Set explicit application/json Content-Type header for REST API operations

### PR DESCRIPTION
**Pull request by rgriffith**
Ensures proper request format when issuing REST API operations.

### CODE REVIEW

**Comment by bradical** [comment]
What did we decide to do  with this PR? I know we made some changes to the filter we were using in Cascade itself.

**Comment by bradical** [comment]
@rgriffith did you want to do something with this PR?

**Comment by rgriffith** [comment]
I stumbled on this one earlier. I'll clean up the unused imports, catch it up and merge.

**Comment by rgriffith** [comment]
Looks like this was already added 961b0f71e112ac40905aeef875b756f6c4d98407. Closing/deleting.

**Pull request closed without merging**
